# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-04 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maldini', '0002_foldermark'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='push',
            field=models.BooleanField(default=False),
        ),
    ]
