# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-04 14:32
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maldini', '0003_document_push'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='status',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
