# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 17:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maldini', '0004_document_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=1000)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maldini.Document')),
            ],
        ),
        migrations.AlterIndexTogether(
            name='prop',
            index_together=set([('key', 'value')]),
        ),
    ]
