# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maldini', '0008_auto_20160511_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prop',
            name='value',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
