# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 22:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maldini', '0009_auto_20160511_0053'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prop',
            unique_together=set([]),
        ),
        migrations.AlterIndexTogether(
            name='prop',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='prop',
            name='document',
        ),
        migrations.DeleteModel(
            name='Prop',
        ),
    ]
