# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 18:00
from __future__ import unicode_literals

from django.db import migrations, models, connection


def copy_digests(apps, schema_editor):
    cursor = connection.cursor()
    cursor.execute(
        'INSERT INTO maldini_digest(id, data) '
        'SELECT document_id, data FROM maldini_cache'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('maldini', '0012_failure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Digest',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('data', models.TextField()),
            ],
        ),
        migrations.RunPython(copy_digests),
    ]
