# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 18:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maldini', '0013_digest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cache',
            name='document',
        ),
        migrations.RemoveField(
            model_name='failure',
            name='document',
        ),
        migrations.RemoveField(
            model_name='generation',
            name='document',
        ),
        migrations.RemoveField(
            model_name='document',
            name='push',
        ),
        migrations.RemoveField(
            model_name='document',
            name='status',
        ),
        migrations.DeleteModel(
            name='Cache',
        ),
        migrations.DeleteModel(
            name='Failure',
        ),
        migrations.DeleteModel(
            name='Generation',
        ),
    ]
