# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('maldini', '0014_auto_20160526_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='digest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
