# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 18:38
from __future__ import unicode_literals

from django.db import migrations


def setup_pq(apps, schema_editor):
    from maldini.queue import _create
    _create()


def cleanup_pq(apps, schema_editor):
    from maldini.queue import _cleanup
    _cleanup()


class Migration(migrations.Migration):

    dependencies = [
        ('maldini', '0016_error'),
    ]

    operations = [
        migrations.RunPython(setup_pq, cleanup_pq),
    ]
