# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 18:38
from __future__ import unicode_literals

from django.db import migrations, connection, transaction


def setup_pq(apps, schema_editor):
    import pq
    @contextmanager
    def django_transaction(conn, **kwargs):
        assert conn is connection
        with transaction.atomic():
            yield conn.cursor(**kwargs)

    pq.transaction = django_transaction
    pq.PQ(connection).create()


def cleanup_pq(apps, schema_editor):
    cursor = connection.cursor()
    cursor.execute('drop table queue')
    cursor.execute('drop function pq_notify()')


class Migration(migrations.Migration):

    dependencies = [
        ('maldini', '0016_error'),
    ]

    operations = [
#        migrations.RunPython(setup_pq, cleanup_pq),
    ]
