# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 21:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maldini', '0017_auto_20160526_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='error',
            name='data',
        ),
    ]
