# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maldini', '0019_auto_20160527_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
