# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maldini', '0022_auto_20160531_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='md5',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='sha1',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
