# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-18 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maldini', '0023_auto_20160615_0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='TikaCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha1', models.CharField(db_index=True, max_length=50)),
                ('data', models.TextField()),
            ],
        ),
    ]
