# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-18 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maldini', '0023_auto_20160615_0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='TikaCache',
            fields=[
                ('sha1', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('data', models.TextField()),
            ],
        ),
    ]
