# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-19 18:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maldini', '0025_auto_20160618_1746'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Error',
        ),
    ]
