# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-19 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maldini', '0026_delete_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='filename',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
