# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maldini', '0029_auto_20160621_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='broken',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
