# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maldini', '0030_document_broken'),
    ]

    operations = [
        migrations.CreateModel(
            name='TikaLangCache',
            fields=[
                ('sha1', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('lang', models.CharField(max_length=20)),
            ],
        ),
    ]
