# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maldini', '0031_tikalangcache'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tikacache',
            old_name='data',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='tikalangcache',
            old_name='lang',
            new_name='value',
        ),
    ]
