# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maldini', '0032_auto_20160625_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCache',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('value', models.TextField()),
            ],
        ),
    ]
