# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maldini', '0033_emailcache'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='rev',
            field=models.IntegerField(null=True),
        ),
    ]
