# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 12:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('maldini', '0034_document_rev'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcache',
            name='time',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 6, 28, 12, 5, 16, 151310, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tikacache',
            name='time',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 6, 28, 12, 5, 17, 394265, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tikalangcache',
            name='time',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 6, 28, 12, 5, 18, 170790, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
