# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 15:37
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maldini', '0037_auto_20160630_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='flags',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
