# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maldini', '0038_document_flags'),
    ]

    operations = [
        migrations.CreateModel(
            name='HtmlTextCache',
            fields=[
                ('sha1', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
