# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-10 18:05
from __future__ import unicode_literals

from django.db import migrations, connection

TABLES = [
    'archivelistcache',
    'digest',
    'document',
    'emailcache',
    'foldermark',
    'htmltextcache',
    'job',
    'ocr',
    'tikacache',
    'tikalangcache',
]


def swap_tables(apps, schema_editor):
    cursor = connection.cursor()
    for table in TABLES:
        sql = lambda statement: cursor.execute(statement)
        sql('ALTER TABLE maldini_{0} RENAME TO maldini_tmp_{0}'.format(table))
        sql('ALTER TABLE snoop_{0} RENAME TO maldini_{0}'.format(table))
        sql('ALTER TABLE maldini_tmp_{0} RENAME TO snoop_{0}'.format(table))


class Migration(migrations.Migration):

    dependencies = [
        ('maldini', '0040_htmltextcache'),
        ('snoop', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(swap_tables, swap_tables),
    ]
