# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-10 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maldini', '0041_swap_tables'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArchiveListCache',
        ),
        migrations.DeleteModel(
            name='Digest',
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='document',
            name='container',
        ),
        migrations.DeleteModel(
            name='EmailCache',
        ),
        migrations.DeleteModel(
            name='FolderMark',
        ),
        migrations.DeleteModel(
            name='HtmlTextCache',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='Ocr',
        ),
        migrations.DeleteModel(
            name='TikaCache',
        ),
        migrations.DeleteModel(
            name='TikaLangCache',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
