# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-17 12:32
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md5', models.BinaryField(db_index=True, max_length=16)),
                ('sha1', models.BinaryField(db_index=True, max_length=20)),
                ('sha3_256', models.BinaryField(max_length=32, unique=True)),
                ('size', models.BigIntegerField()),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('mime_encoding', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root', models.CharField(max_length=4000)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ocr', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename_bytes', models.BinaryField(max_length=1000)),
                ('blob', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snoop.Blob')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snoop.Collection')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_set', to='snoop.Document')),
            ],
        ),
        migrations.CreateModel(
            name='Ocr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('md5', models.CharField(db_index=True, max_length=40)),
                ('path', models.CharField(max_length=4000)),
                ('text', models.TextField(blank=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_documents', to='snoop.Collection')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='ocr',
            unique_together=set([('collection', 'tag', 'md5')]),
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together=set([('parent', 'filename_bytes')]),
        ),
    ]
