# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-03 07:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snoop', '0002_refactor_broken_exceptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_set', to='snoop.Document'),
        ),
        migrations.AlterField(
            model_name='document',
            name='container',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contained_set', to='snoop.Document'),
        ),
    ]
