# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-01 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snoop', '0002_refactor_broken_exceptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='rev',
        ),
        migrations.AddField(
            model_name='document',
            name='last_digest',
            field=models.DateTimeField(null=True),
        ),
    ]
