# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-04 08:25
from __future__ import unicode_literals

from django.db import migrations

UPDATE_PARENT_ID = """
    update snoop_document as doc set parent_id = case
      when path like '%/%' then
        (select id from temp_folder as tmp where
          tmp.path = regexp_replace(doc.path, '/[^/]*$', '') and
          (
            tmp.container_id = doc.container_id or
            (
              tmp.container_id is null and
              tmp.container_id is null
            )
          )
        )
      when container_id is not null then
        container_id
      when path != '' then
        (select id from temp_folder where container_id is null and path = '')
      else
        null
      end
"""

POPULATE_TABLE_TEMP_FOLDER = """
insert into temp_folder(id, container_id, path)
  select id, container_id, path
  from snoop_document
  where content_type = 'application/x-directory'
"""

CREATE_TABLE_TEMP_FOLDER = """create table temp_folder(
  id integer PRIMARY KEY,
  container_id integer,
  path text NOT NULL
)
"""

DROP_TABLE_TEMP_FOLDER = 'drop table temp_folder'

INSERT_ROOT = """
  insert into snoop_document(
    path,
    filename,
    disk_size,
    content_type,
    md5,
    sha1,
    broken,
    flags
  ) values (
    '',
    '',
    0,
    'application/x-directory',
    'd41d8cd98f00b204e9800998ecf8427e',
    'da39a3ee5e6b4b0d3255bfef95601890afd80709',
    '',
    '{}'
  )
"""
DELETE_ROOT = """
  delete from snoop_document where
    path = '' and filename = '' and content_type = 'application/x-directory'
"""


class Migration(migrations.Migration):

    dependencies = [
        ('snoop', '0003_auto_20161003_0755'),
    ]

    operations = [
        migrations.RunSQL( # create root document
            INSERT_ROOT,
            DELETE_ROOT,
        ),
        migrations.RunSQL( # create temporary table with id, path
            CREATE_TABLE_TEMP_FOLDER,
            DROP_TABLE_TEMP_FOLDER,
        ),
        migrations.RunSQL(  # index on temp table's path
            "create index temp_folder_path_idx on temp_folder(container_id, path)",
            "drop index if exists temp_folder_path_idx",
        ),
        migrations.RunSQL( # populate the temp table with id, path from snoop_document
            POPULATE_TABLE_TEMP_FOLDER,
            "delete from temp_folder",
        ),
        migrations.RunSQL( # fill snoop_document.parent_id
            UPDATE_PARENT_ID,
            "update snoop_document set parent_id = null",
        ),
        migrations.RunSQL(  # drop the temporary table
            DROP_TABLE_TEMP_FOLDER,
            CREATE_TABLE_TEMP_FOLDER,
        )
    ]
