# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-08 11:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snoop', '0004_auto_20161004_0825'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArchiveListCache',
        ),
    ]
