# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-26 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snoop', '0007_auto_20161026_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='slug',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
