# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-26 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snoop', '0008_auto_20161026_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
