# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snoop', '0009_collection_ocr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ocr',
            old_name='tag',
            new_name='key',
        ),
        migrations.AddField(
            model_name='ocr',
            name='collection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ocr_documents', to='snoop.Collection'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='ocr',
            unique_together=set([('collection', 'key', 'md5')]),
        ),
    ]
