# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-15 09:27
from __future__ import unicode_literals

from django.db import migrations, models


sql_forward = """\
UPDATE snoop_document
    SET digested_at = snoop_digest.updated_at
    FROM snoop_digest
    WHERE snoop_document.id = snoop_digest.id
"""


sql_reverse = """\
UPDATE snoop_digest
    SET updated_at = snoop_document.digested_at
    FROM snoop_document
    WHERE snoop_digest.id = snoop_document.id
"""


class Migration(migrations.Migration):

    dependencies = [
        ('snoop', '0010_auto_20161121_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='digested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterIndexTogether(
            name='document',
            index_together=set([('collection', 'digested_at')]),
        ),
        migrations.RunSQL(sql_forward, sql_reverse),
        migrations.RemoveField(
            model_name='digest',
            name='updated_at',
        ),
    ]
